using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using RotationsPlus.Api.Infrastructure;
using RotationsPlus.Common.Authorization;
using RotationsPlus.Common.Security;
using RotationsPlus.Contracts.Payments;

namespace RotationsPlus.Api.Modules.Payments;

/// <summary>
/// Admin honorarium screen endpoints (/admin/honorarium): the preceptor payout queue, split into the three
/// stage tabs (Deposit / Start / Evaluation). AdminOnly throughout — honorarium is admin-only in the authz
/// matrix. Rows are generated by <see cref="HonorariumGenerator"/> on deposit success; here an admin pays a
/// stage (bookkeeping mark, gated so stages are paid in order) and toggles the refunded flag.
/// </summary>
public static class HonorariumEndpoints
{
    public static IEndpointRouteBuilder MapHonorariumEndpoints(this IEndpointRouteBuilder routes)
    {
        var group = routes.MapGroup("/api/honorariums")
            .RequireAuthorization(AuthorizationPolicies.AdminOnly)
            .WithTags("Payments");

        // The three-tab list. `stage` selects the tab; `status` optionally narrows (e.g. show only Pending).
        // `q` searches preceptor/student name. Ordered by rotation start date then id for deterministic paging.
        group.MapGet("/", async (
            HonorariumStage? stage, HonorariumStatus? status, string? q, int? page, int? pageSize,
            RotationsDbContext db, CancellationToken cancellationToken) =>
        {
            if (!PaginationExtensions.TryBuildSearchPattern(q, out var pattern, out var searchError))
            {
                return Results.BadRequest(searchError);
            }

            var query = db.Honorariums.AsQueryable();
            if (stage is { } st) query = query.Where(h => h.Stage == st);
            if (status is { } stat) query = query.Where(h => h.Status == stat);
            if (pattern is not null)
            {
                query = query.Where(h =>
                    EF.Functions.ILike(h.PreceptorName, pattern) ||
                    EF.Functions.ILike(h.StudentName, pattern));
            }

            var honorariums = await query
                .OrderBy(h => h.RotationStartDate)
                .ThenBy(h => h.Id) // tie-break so paging is deterministic when start dates collide
                .Select(Summary)
                .ToPagedResponseAsync(page, pageSize, cancellationToken);

            return Results.Ok(honorariums);
        })
        .WithName("ListHonorariums");

        // Mark a stage paid (bookkeeping — no gateway money movement). Only a Pending stage is payable; the
        // stages must be paid IN ORDER (Start needs Deposit paid; Evaluation needs Start paid), mirroring the
        // legacy "is payment available" gate. Stamps who paid it and when.
        group.MapPost("/{id:guid}/pay", async (
            Guid id, RotationsDbContext db, ICurrentUser user, TimeProvider clock, CancellationToken cancellationToken) =>
        {
            var honorarium = await db.Honorariums.FirstOrDefaultAsync(h => h.Id == id, cancellationToken);
            if (honorarium is null)
            {
                return Results.NotFound();
            }
            if (honorarium.Status != HonorariumStatus.Pending)
            {
                return Results.Conflict("Only a pending honorarium can be paid.");
            }

            if (honorarium.Stage != HonorariumStage.Deposit)
            {
                var previousStage = honorarium.Stage == HonorariumStage.Evaluation
                    ? HonorariumStage.Start
                    : HonorariumStage.Deposit;
                // The prior stage must already be Paid. (A missing prior stage — e.g. a partially generated
                // schedule — also blocks, which is the safe default for a payout gate.)
                var previousPaid = await db.Honorariums.AnyAsync(
                    h => h.RotationId == honorarium.RotationId
                        && h.Stage == previousStage
                        && h.Status == HonorariumStatus.Paid,
                    cancellationToken);
                if (!previousPaid)
                {
                    return Results.Conflict("The previous honorarium stage must be paid first.");
                }
            }

            honorarium.Status = HonorariumStatus.Paid;
            honorarium.PaidAtUtc = clock.GetUtcNow();
            honorarium.PaidBy = user.ObjectId;
            await db.SaveChangesAsync(cancellationToken);

            return Results.Ok(ToResponse(honorarium));
        })
        .WithName("PayHonorarium");

        // Toggle the independent refunded bookkeeping flag (legacy checkbox). Does not move money or change
        // the paid status — it just records that the payout was/should be reversed.
        group.MapPost("/{id:guid}/refund-flag", async (
            Guid id, SetHonorariumRefundRequest request, RotationsDbContext db, CancellationToken cancellationToken) =>
        {
            var honorarium = await db.Honorariums.FirstOrDefaultAsync(h => h.Id == id, cancellationToken);
            if (honorarium is null)
            {
                return Results.NotFound();
            }

            honorarium.Refunded = request.Refunded;
            await db.SaveChangesAsync(cancellationToken);

            return Results.Ok(ToResponse(honorarium));
        })
        .WithName("SetHonorariumRefundFlag");

        // Remove an erroneously-generated payout row (soft-delete). Guarded: a PAID stage can't be deleted
        // (the money is recorded as disbursed — deleting it would lose the audit trail), so only a Pending/
        // Cancelled row is removable. Soft-delete keeps the row out of the live unique (RotationId, Stage)
        // index and the list, and generation never re-creates it (the IgnoreQueryFilters existence check
        // still sees the soft-deleted row).
        group.MapDelete("/{id:guid}", async (Guid id, RotationsDbContext db, CancellationToken cancellationToken) =>
        {
            var honorarium = await db.Honorariums.FirstOrDefaultAsync(h => h.Id == id, cancellationToken);
            if (honorarium is null)
            {
                return Results.NotFound();
            }
            if (honorarium.Status == HonorariumStatus.Paid)
            {
                return Results.Conflict("A paid honorarium can't be deleted.");
            }

            db.Honorariums.Remove(honorarium); // interceptor converts the delete into a soft-delete
            await db.SaveChangesAsync(cancellationToken);
            return Results.NoContent();
        })
        .WithName("DeleteHonorarium");

        return routes;
    }

    private static HonorariumResponse ToResponse(Honorarium h) =>
        new(h.Id, h.RotationId, h.RotationNumber, h.PreceptorId, h.PreceptorName, h.StudentName,
            h.Stage, h.Amount, h.Currency, h.Status, h.Refunded, h.RotationStartDate, h.PaidAtUtc);

    // List projection. A plain expression over scalar columns (no navigations), so a compiled
    // Expression keeps the projection in SQL and there's no client-eval surprise.
    private static readonly Expression<Func<Honorarium, HonorariumResponse>> Summary =
        h => new HonorariumResponse(
            h.Id, h.RotationId, h.RotationNumber, h.PreceptorId, h.PreceptorName, h.StudentName,
            h.Stage, h.Amount, h.Currency, h.Status, h.Refunded, h.RotationStartDate, h.PaidAtUtc);
}
