// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RotationsPlus.Api.Infrastructure;

#nullable disable

namespace RotationsPlus.Api.Infrastructure.Migrations
{
    [DbContext(typeof(RotationsDbContext))]
    [Migration("20260626165530_AddHonorariums")]
    partial class AddHonorariums
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RotationsPlus.Api.Modules.Crm.CampaignRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AttemptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Error")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "Email")
                        .IsUnique();

                    b.HasIndex("CampaignId", "Status");

                    b.ToTable("campaign_recipients", "crm");
                });

            modelBuilder.Entity("RotationsPlus.Api.Modules.Crm.EmailCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("RecipientCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SendStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SentCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("email_campaigns", "crm");
                });

            modelBuilder.Entity("RotationsPlus.Api.Modules.Documents.DocumentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("document_types", "documents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0c00000-0000-0000-0000-000000000001"),
                            Category = "Immunization",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "COVID-19 Vaccine"
                        },
                        new
                        {
                            Id = new Guid("d0c00000-0000-0000-0000-000000000002"),
                            Category = "Immunization",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "Hepatitis B"
                        },
                        new
                        {
                            Id = new Guid("d0c00000-0000-0000-0000-000000000003"),
                            Category = "Immunization",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "MMR (Measles/Mumps/Rubella)"
                        },
                        new
                        {
                            Id = new Guid("d0c00000-0000-0000-0000-000000000004"),
                            Category = "Immunization",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "Varicella"
                        },
                        new
                        {
                            Id = new Guid("d0c00000-0000-0000-0000-000000000005"),
                            Category = "Immunization",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "Tdap"
                        },
                        new
                        {
                            Id = new Guid("d0c00000-0000-0000-0000-000000000006"),
                            Category = "MedicalTest",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "TB Test (PPD/Quantiferon)"
                        },
                        new
                        {
                            Id = new Guid("d0c00000-0000-0000-0000-000000000007"),
                            Category = "MedicalTest",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "10-Panel Drug Screen"
                        },
                        new
                        {
                            Id = new Guid("d0c00000-0000-0000-0000-000000000008"),
                            Category = "Identity",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "Proof of Identity"
                        },
                        new
                        {
                            Id = new Guid("d0c00000-0000-0000-0000-000000000009"),
                            Category = "Insurance",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "Proof of Health Insurance"
                        },
                        new
                        {
                            Id = new Guid("d0c00000-0000-0000-0000-00000000000a"),
                            Category = "Insurance",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "Proof of Liability Insurance"
                        },
                        new
                        {
                            Id = new Guid("d0c00000-0000-0000-0000-00000000000b"),
                            Category = "Certification",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "Basic Life Support (BLS)"
                        },
                        new
                        {
                            Id = new Guid("d0c00000-0000-0000-0000-00000000000c"),
                            Category = "Certification",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "HIPAA Training"
                        },
                        new
                        {
                            Id = new Guid("d0c00000-0000-0000-0000-00000000000d"),
                            Category = "Professional",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "Curriculum Vitae (CV)"
                        },
                        new
                        {
                            Id = new Guid("d0c00000-0000-0000-0000-00000000000e"),
                            Category = "Professional",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "Photo for ID Badge"
                        });
                });

            modelBuilder.Entity("RotationsPlus.Api.Modules.Documents.ProgramRequiredDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("ProgramId", "DocumentTypeId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("program_required_documents", "documents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d12e0000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            DocumentTypeId = new Guid("d0c00000-0000-0000-0000-000000000001"),
                            IsDeleted = false,
                            ProgramId = new Guid("cccccccc-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("d12e0000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            DocumentTypeId = new Guid("d0c00000-0000-0000-0000-000000000008"),
                            IsDeleted = false,
                            ProgramId = new Guid("cccccccc-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("d12e0000-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            DocumentTypeId = new Guid("d0c00000-0000-0000-0000-00000000000b"),
                            IsDeleted = false,
                            ProgramId = new Guid("cccccccc-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("d12e0000-0000-0000-0000-000000000004"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            DocumentTypeId = new Guid("d0c00000-0000-0000-0000-00000000000d"),
                            IsDeleted = false,
                            ProgramId = new Guid("cccccccc-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("RotationsPlus.Api.Modules.Documents.RotationDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("FileBlobName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FileName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("RotationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("StudentId");

                    b.HasIndex("RotationId", "DocumentTypeId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("rotation_documents", "documents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d40c0000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            DocumentTypeId = new Guid("d0c00000-0000-0000-0000-000000000001"),
                            DueDate = new DateOnly(2026, 6, 22),
                            FileName = "covid-card.pdf",
                            IsDeleted = false,
                            RotationId = new Guid("eeeeeeee-0000-0000-0000-000000000001"),
                            Status = "Approved",
                            StudentId = new Guid("ffffffff-0000-0000-0000-000000000001"),
                            SubmittedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("d40c0000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            DocumentTypeId = new Guid("d0c00000-0000-0000-0000-000000000008"),
                            DueDate = new DateOnly(2026, 6, 22),
                            FileName = "passport.pdf",
                            IsDeleted = false,
                            RotationId = new Guid("eeeeeeee-0000-0000-0000-000000000001"),
                            Status = "Submitted",
                            StudentId = new Guid("ffffffff-0000-0000-0000-000000000001"),
                            SubmittedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("d40c0000-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            DocumentTypeId = new Guid("d0c00000-0000-0000-0000-00000000000b"),
                            DueDate = new DateOnly(2026, 6, 22),
                            IsDeleted = false,
                            RotationId = new Guid("eeeeeeee-0000-0000-0000-000000000001"),
                            Status = "UploadNeeded",
                            StudentId = new Guid("ffffffff-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("d40c0000-0000-0000-0000-000000000004"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            DocumentTypeId = new Guid("d0c00000-0000-0000-0000-00000000000d"),
                            DueDate = new DateOnly(2026, 6, 22),
                            IsDeleted = false,
                            RotationId = new Guid("eeeeeeee-0000-0000-0000-000000000001"),
                            Status = "UploadNeeded",
                            StudentId = new Guid("ffffffff-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("RotationsPlus.Api.Modules.Identity.StaffProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("EntraObjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSignInAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("EntraObjectId")
                        .IsUnique();

                    b.ToTable("staff_profiles", "identity");
                });

            modelBuilder.Entity("RotationsPlus.Api.Modules.Marketplace.Preceptor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LicenseState")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MedicalLicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("PrimarySpecialtyId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PrimarySpecialtyId");

                    b.ToTable("preceptors", "marketplace");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-0000-0000-0000-000000000001"),
                            City = "Chicago",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Email = "jane.carter@example.com",
                            FirstName = "Jane",
                            IsDeleted = false,
                            LastName = "Carter",
                            LicenseState = "IL",
                            PrimarySpecialtyId = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            State = "IL",
                            Status = "MemberActivated"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-0000-0000-0000-000000000002"),
                            City = "Houston",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Email = "omar.reyes@example.com",
                            FirstName = "Omar",
                            IsDeleted = false,
                            LastName = "Reyes",
                            LicenseState = "TX",
                            PrimarySpecialtyId = new Guid("aaaaaaaa-0000-0000-0000-000000000007"),
                            State = "TX",
                            Status = "MemberValidated"
                        });
                });

            modelBuilder.Entity("RotationsPlus.Api.Modules.Marketplace.RotationProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("DocumentDueDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(14);

                    b.Property<string>("ImageBlobName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxStudentsPerRotation")
                        .HasColumnType("integer");

                    b.Property<int>("MinWeeksPerRotation")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("PreceptorId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProgramNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProgramNumber"));

                    b.Property<string>("ProgramType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("RetailAmountPerWeek")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'");

                    b.Property<decimal>("WeeklyHonorarium")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("PreceptorId");

                    b.HasIndex("ProgramNumber")
                        .IsUnique();

                    b.HasIndex("SpecialtyId");

                    b.ToTable("programs", "marketplace");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-000000000001"),
                            City = "Los Angeles",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Description = "In-person internal medicine rotation.",
                            DocumentDueDays = 14,
                            IsDeleted = false,
                            IsOpen = false,
                            MaxStudentsPerRotation = 2,
                            MinWeeksPerRotation = 4,
                            PreceptorId = new Guid("dddddddd-0000-0000-0000-000000000001"),
                            ProgramNumber = 1001,
                            ProgramType = "InPerson",
                            RetailAmountPerWeek = 1500m,
                            SpecialtyId = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            State = "CA",
                            WeeklyHonorarium = 500m
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-000000000002"),
                            City = "Remote",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Description = "Remote internal medicine tele-rotation.",
                            DocumentDueDays = 14,
                            IsDeleted = false,
                            IsOpen = true,
                            MaxStudentsPerRotation = 4,
                            MinWeeksPerRotation = 2,
                            PreceptorId = new Guid("dddddddd-0000-0000-0000-000000000001"),
                            ProgramNumber = 1002,
                            ProgramType = "TeleRotation",
                            RetailAmountPerWeek = 1000m,
                            SpecialtyId = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            State = "NY",
                            WeeklyHonorarium = 300m
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-000000000003"),
                            City = "Houston",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Description = "Hands-on pediatrics rotation.",
                            DocumentDueDays = 14,
                            IsDeleted = false,
                            IsOpen = false,
                            MaxStudentsPerRotation = 1,
                            MinWeeksPerRotation = 4,
                            PreceptorId = new Guid("dddddddd-0000-0000-0000-000000000002"),
                            ProgramNumber = 1003,
                            ProgramType = "InPerson",
                            RetailAmountPerWeek = 1800m,
                            SpecialtyId = new Guid("aaaaaaaa-0000-0000-0000-000000000007"),
                            State = "TX",
                            WeeklyHonorarium = 600m
                        },
                        new
                        {
                            Id = new Guid("cccccccc-0000-0000-0000-000000000004"),
                            City = "Chicago",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Description = "Family medicine consultation rotation.",
                            DocumentDueDays = 14,
                            IsDeleted = false,
                            IsOpen = false,
                            MaxStudentsPerRotation = 3,
                            MinWeeksPerRotation = 2,
                            ProgramNumber = 1004,
                            ProgramType = "Consultation",
                            RetailAmountPerWeek = 900m,
                            SpecialtyId = new Guid("aaaaaaaa-0000-0000-0000-000000000003"),
                            State = "IL",
                            WeeklyHonorarium = 250m
                        });
                });

            modelBuilder.Entity("RotationsPlus.Api.Modules.Marketplace.Specialty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("specialties", "marketplace");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "Internal Medicine"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "General Surgery"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "Family Medicine"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000004"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "Psychiatry"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000005"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "Neurology"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000006"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "Pathology"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000007"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000008"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "OBGYN"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000009"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "Orthopedic Surgery"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-00000000000a"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "Radiology"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-00000000000b"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "Anesthesiology"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-00000000000c"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "Dermatology"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-00000000000d"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "Emergency Medicine"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-00000000000e"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "Hematology/Oncology"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-00000000000f"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "All Core Rotations"
                        });
                });

            modelBuilder.Entity("RotationsPlus.Api.Modules.Payments.Honorarium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaidBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("PreceptorId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreceptorName")
                        .IsRequired()
                        .HasMaxLength(201)
                        .HasColumnType("character varying(201)");

                    b.Property<bool>("Refunded")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RotationId")
                        .HasColumnType("uuid");

                    b.Property<int>("RotationNumber")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("RotationStartDate")
                        .HasColumnType("date");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(201)
                        .HasColumnType("character varying(201)");

                    b.HasKey("Id");

                    b.HasIndex("RotationId", "Stage")
                        .IsUnique()
                        .HasDatabaseName("UX_honorariums_RotationId_Stage_live")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("Stage", "RotationStartDate", "Id")
                        .HasDatabaseName("IX_honorariums_Stage_RotationStartDate_Id_live")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("honorariums", "payments");
                });

            modelBuilder.Entity("RotationsPlus.Api.Modules.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("OutstandingAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("ProviderPaymentIntentId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ProviderRefundId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("RotationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("ProviderPaymentIntentId")
                        .IsUnique()
                        .HasFilter("\"ProviderPaymentIntentId\" IS NOT NULL AND \"IsDeleted\" = false");

                    b.HasIndex("RotationId")
                        .IsUnique()
                        .HasDatabaseName("UX_payments_RotationId_active")
                        .HasFilter("\"IsDeleted\" = false AND \"Status\" IN ('Pending', 'Succeeded')");

                    b.ToTable("payments", "payments");
                });

            modelBuilder.Entity("RotationsPlus.Api.Modules.Payments.ProcessedWebhookEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("processed_webhook_events", "payments");
                });

            modelBuilder.Entity("RotationsPlus.Api.Modules.Rotations.Rotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<int>("RotationNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RotationNumber"));

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StudentEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("StudentOid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Weeks")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.HasIndex("RotationNumber")
                        .IsUnique();

                    b.HasIndex("StartDate")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("StudentId");

                    b.HasIndex("Status", "StartDate")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("rotations", "operations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeeeeeee-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            EndDate = new DateOnly(2026, 8, 3),
                            IsDeleted = false,
                            ProgramId = new Guid("cccccccc-0000-0000-0000-000000000001"),
                            RotationNumber = 1001,
                            StartDate = new DateOnly(2026, 7, 6),
                            Status = "Active",
                            StudentEmail = "sam.rivera@example.com",
                            StudentId = new Guid("ffffffff-0000-0000-0000-000000000001"),
                            StudentName = "Sam Rivera",
                            Weeks = 4
                        });
                });

            modelBuilder.Entity("RotationsPlus.Api.Modules.Students.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcademicStatus")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MedicalSchool")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MedicalSchoolCountry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MobilePhone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StudentOid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("VisaStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("StudentOid")
                        .IsUnique()
                        .HasFilter("\"StudentOid\" IS NOT NULL AND \"IsDeleted\" = false");

                    b.ToTable("students", "members");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-0000-0000-0000-000000000001"),
                            AcademicStatus = "InternationalMedicalGraduate",
                            City = "Chicago",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Email = "sam.rivera@example.com",
                            FirstName = "Sam",
                            IsDeleted = false,
                            LastName = "Rivera",
                            State = "IL",
                            Status = "MemberActivated",
                            VisaStatus = "NeedsVisaHelp"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-0000-0000-0000-000000000002"),
                            AcademicStatus = "MdStudent",
                            City = "Houston",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "seed",
                            Email = "dana.cole@example.com",
                            FirstName = "Dana",
                            IsDeleted = false,
                            LastName = "Cole",
                            State = "TX",
                            Status = "Registered"
                        });
                });

            modelBuilder.Entity("RotationsPlus.Api.Modules.Documents.ProgramRequiredDocument", b =>
                {
                    b.HasOne("RotationsPlus.Api.Modules.Documents.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RotationsPlus.Api.Modules.Marketplace.RotationProgram", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("RotationsPlus.Api.Modules.Documents.RotationDocument", b =>
                {
                    b.HasOne("RotationsPlus.Api.Modules.Documents.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RotationsPlus.Api.Modules.Rotations.Rotation", "Rotation")
                        .WithMany()
                        .HasForeignKey("RotationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RotationsPlus.Api.Modules.Students.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DocumentType");

                    b.Navigation("Rotation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("RotationsPlus.Api.Modules.Marketplace.Preceptor", b =>
                {
                    b.HasOne("RotationsPlus.Api.Modules.Marketplace.Specialty", "PrimarySpecialty")
                        .WithMany()
                        .HasForeignKey("PrimarySpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PrimarySpecialty");
                });

            modelBuilder.Entity("RotationsPlus.Api.Modules.Marketplace.RotationProgram", b =>
                {
                    b.HasOne("RotationsPlus.Api.Modules.Marketplace.Preceptor", "Preceptor")
                        .WithMany()
                        .HasForeignKey("PreceptorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RotationsPlus.Api.Modules.Marketplace.Specialty", "Specialty")
                        .WithMany()
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Preceptor");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("RotationsPlus.Api.Modules.Payments.Honorarium", b =>
                {
                    b.HasOne("RotationsPlus.Api.Modules.Rotations.Rotation", "Rotation")
                        .WithMany()
                        .HasForeignKey("RotationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rotation");
                });

            modelBuilder.Entity("RotationsPlus.Api.Modules.Payments.Payment", b =>
                {
                    b.HasOne("RotationsPlus.Api.Modules.Rotations.Rotation", "Rotation")
                        .WithMany()
                        .HasForeignKey("RotationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rotation");
                });

            modelBuilder.Entity("RotationsPlus.Api.Modules.Rotations.Rotation", b =>
                {
                    b.HasOne("RotationsPlus.Api.Modules.Marketplace.RotationProgram", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RotationsPlus.Api.Modules.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Program");
                });
#pragma warning restore 612, 618
        }
    }
}
